# Generated by Django 5.2.6 on 2025-09-17 22:05

from django.db import migrations
import os


def ejecutar_script_sql(apps, schema_editor):
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sql_path = os.path.join(base_dir, 'sql', 'datos_iniciales.sql')

    with open(sql_path, 'r', encoding='utf-8') as f:
        sql = f.read()
    schema_editor.execute(sql)

class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(ejecutar_script_sql),
    ]
