# Generated by Django 5.2.6 on 2025-09-16 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly')], max_length=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('total_points', models.IntegerField(default=0)),
                ('total_activities', models.IntegerField(default=0)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.period')),
            ],
        ),
    ]
